// import "~/styles/globals.css";

// import { GeistSans } from "geist/font/sans";
// import { type Metadata } from "next";

// import { TRPCReactProvider } from "~/trpc/react";

// export const metadata: Metadata = {
//   title: "Create T3 App",
//   description: "Generated by create-t3-app",
//   icons: [{ rel: "icon", url: "/favicon.ico" }],
// };

// export default function RootLayout({
//   children,
// }: Readonly<{ children: React.ReactNode }>) {
//   return (
//     <html lang="en" className={`${GeistSans.variable}`}>
//       <body>
//         <TRPCReactProvider>{children}</TRPCReactProvider>
//       </body>
//     </html>
//   );
// }

import "~/styles/globals.css";
import "@fontsource/fira-code";

import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import { clx } from "~/utils";
import { Navbar } from "./navbar";
import { Footer } from "./footer";
import { TechIUse } from "./tech-i-use";
import { ViewTransitions } from "next-view-transitions";

export const metadata: Metadata = {
  metadataBase: new URL("https://khushhh.vercel.app/"),
  title: {
    default: "Khush Shah",
    template: "%s | Khush Shah",
  },
  description: "Developer",
  openGraph: {
    title: "Khush Shah",
    description: "Developer",
    url: "",
    siteName: "Khush Shah",
    locale: "en_US",
    type: "website",
    images: [""],
  },
  robots: {
    index: true,
    follow: true,
    "max-video-preview": -1,
    "max-image-preview": "large",
    "max-snippet": -1,
  },
  // twitter: {
  //   title: "Khush Shah",
  //   card: "summary_large_image",
  //   creator: "@nexxeln",
  // },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ViewTransitions>
      <html
        lang="en"
        className={clx(
          "bg-neutral-100 text-black dark:bg-neutral-950 dark:text-white",
          // "font-fira-code"
          GeistSans.variable,
          GeistMono.variable,
          
        )}
      >
        <body className="mx-4 mb-20 mt-8 flex max-w-2xl flex-col antialiased md:flex-row lg:mx-auto">
          <main className="mt-6 flex min-w-0 flex-auto flex-col px-2 md:px-0">
            <Navbar />
            
            {children}
            {/* <TechIUse/> */}
            <Footer/>
          </main>
        </body>
      </html>
    </ViewTransitions>
  );
}

